# Generated by Django 4.0.5 on 2022-06-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='部门'),
        ),
    ]
