# Generated by Django 4.0.5 on 2022-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_create_time_alter_staff_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='beautyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('rank', models.SmallIntegerField(choices=[(1, '免费用户'), (2, 'vip'), (3, 'Svip')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已占用')], default=0, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='入职时间'),
        ),
    ]
