# Generated by Django 4.0.5 on 2022-06-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_beautyphone_alter_staff_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.beautyphone', verbose_name='手机号'),
        ),
    ]
